import Providers from "@modules/providers"
import "@/css/globals.css"
import {Inter, Architects_Daughter, Poppins} from 'next/font/google';
import 'flowbite';
import BreakpointsIndicator from "@/components/helper/breakpoints";
import Header from "@/components/ui/Header";
import {ProvidersNextUI} from "@/app/providers";


const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap',
});

const architects_daughter = Architects_Daughter({
    subsets: ['latin'],
    variable: '--font-architects-daughter',
    weight: '400',
    display: 'swap',
});

const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ['latin'],
    variable: '--font-poppins',
    display: 'swap'
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

type RootLayoutProps = {
    children: React.ReactNode;

};

export default function RootLayout({children}: RootLayoutProps) {
    return (
        <html lang="en" className="dark border-2 border-amberA-12 ">
        <body
            className={`${inter.variable} ${poppins.variable}  ${architects_daughter.variable} bg-gray-900  font-inter tracking-tight  antialiased`}
        >
        {/*<BreakpointsIndicator />*/}
        <ProvidersNextUI>
            <Providers>
                <div className="flex min-h-screen flex-col overflow-hidden bg-cyan-1 3xs:pt-[74px] lg:pt-[104px]">
                    {children}
                </div>
            </Providers>
        </ProvidersNextUI>
        </body>
        </html>
    );
}

